name: study_smart_qc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  google_sign_in: 6.2.1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  provider: ^6.1.5+1
  flutter_markdown: ^0.7.4  # For structure (bold, lists)
  flutter_math_fork: ^0.7.2 # For rendering LaTeX equations efficiently
  flutter_tex: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: "^2.3.10"
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_bg.png
  android_12:
    image: assets/splash_bg.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/app_icon.png
    - assets/splash_bg.png